package com.quantumdeepcalm.ai.playback

import android.content.Context
import com.quantumdeepcalm.ai.SessionAudioProfile
import java.io.File

/**
 * Compatibility facade for the existing player integration.
 *
 * Product audio is generated by [ContinuousAudioEngine]; the historical short-loop
 * generator has been removed. Keeping this narrow facade avoids mixing the audio-engine
 * migration with unrelated Compose player changes in the same roadmap item.
 */
internal object CalmAudioGenerator {
    fun ensureGeneratedFile(
        context: Context,
        sessionId: String,
        profile: SessionAudioProfile,
    ): File = ContinuousAudioEngine.ensureGeneratedFile(
        context = context,
        sessionId = sessionId,
        profile = profile,
    )
}
